-- Perbaikan drift skema live: tabel `progress_materi` di Supabase production
-- ternyata dibuat dengan SEMUA kolom bertipe `text` (guru_id, materi_id,
-- progress, last_opened, id) -- tidak cocok dengan definisi di
-- supabase_schema.sql (SERIAL/INT/INT/INT/TIMESTAMP). Ini kelas bug yang sama
-- dengan drift `paket_soal` yang ditemukan saat migrasi Revisi 8 (lihat guard
-- block di supabase_migration_v2_pivot.sql) -- kemungkinan besar tabel ini
-- juga pernah dibuat/diubah manual lewat Table Editor.
--
-- Dampak: GET /api/materi 500 ("operator does not exist: text = bigint")
-- karena JOIN `p.materi_id = m.id` membandingkan text (p.materi_id) dengan
-- bigint (m.id) -- keduanya kolom bertipe tegas, tidak ada literal "unknown"
-- untuk Postgres infer secara implisit, jadi operator = memang tidak ada.
--
-- Aman dijalankan: tabel `progress_materi` masih 0 baris di production saat
-- bug ini ditemukan (2026-08-12), jadi tidak ada risiko cast data gagal.
-- Idempotent lewat guard IF NOT EXISTS pada tiap constraint.

BEGIN;

-- Guard tambahan: `materi.id` juga ternyata tidak punya PRIMARY KEY di live
-- (sama seperti drift `paket_soal.id` yang ditemukan sebelumnya) -- perlu PK
-- sebelum bisa dijadikan target FOREIGN KEY dari progress_materi.materi_id.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'materi'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE materi ADD PRIMARY KEY (id);
  END IF;
END $$;

ALTER TABLE progress_materi ALTER COLUMN guru_id TYPE BIGINT USING guru_id::BIGINT;
ALTER TABLE progress_materi ALTER COLUMN materi_id TYPE BIGINT USING materi_id::BIGINT;
ALTER TABLE progress_materi ALTER COLUMN progress TYPE INTEGER USING progress::INTEGER;
ALTER TABLE progress_materi ALTER COLUMN progress SET DEFAULT 0;
ALTER TABLE progress_materi ALTER COLUMN last_opened TYPE TIMESTAMPTZ USING last_opened::TIMESTAMPTZ;
ALTER TABLE progress_materi ALTER COLUMN guru_id SET NOT NULL;
ALTER TABLE progress_materi ALTER COLUMN materi_id SET NOT NULL;
ALTER TABLE progress_materi ALTER COLUMN id TYPE BIGINT USING id::BIGINT;
ALTER TABLE progress_materi ALTER COLUMN id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'progress_materi' AND column_name = 'id' AND is_identity = 'YES'
  ) THEN
    ALTER TABLE progress_materi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'progress_materi'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE progress_materi ADD PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'progress_materi'::regclass AND contype = 'f' AND conname = 'progress_materi_guru_id_fkey'
  ) THEN
    ALTER TABLE progress_materi
      ADD CONSTRAINT progress_materi_guru_id_fkey FOREIGN KEY (guru_id) REFERENCES guru(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'progress_materi'::regclass AND contype = 'f' AND conname = 'progress_materi_materi_id_fkey'
  ) THEN
    ALTER TABLE progress_materi
      ADD CONSTRAINT progress_materi_materi_id_fkey FOREIGN KEY (materi_id) REFERENCES materi(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'progress_materi'::regclass AND contype = 'u' AND conname = 'progress_materi_guru_id_materi_id_key'
  ) THEN
    ALTER TABLE progress_materi
      ADD CONSTRAINT progress_materi_guru_id_materi_id_key UNIQUE (guru_id, materi_id);
  END IF;
END $$;

COMMIT;
