-- Migrasi Revisi 8 (lihat PIVOT_PLAN.md §B3): menambah split TKA/Non-TKA,
-- melepas kepemilikan paket_soal dari guru perorangan, dan menyiapkan tabel
-- butir soal + hasil diagnostik.
--
-- STATUS: DRAFT — belum dijalankan ke Supabase live. Review dulu (terutama
-- pertanyaan terbuka di PIVOT_PLAN.md §D) sebelum dieksekusi.
-- Jalankan SETELAH supabase_schema.sql (dan supabase_seed_data.sql jika ada
-- data lama yang mau dipertahankan).

BEGIN;

-- ============================================================================
-- 0. Guard: pastikan paket_soal.id punya PRIMARY KEY sebelum tabel lain
--    mereferensikannya lewat FOREIGN KEY. Tabel ini kemungkinan dulu dibuat
--    lewat Table Editor Supabase (bukan persis dari supabase_schema.sql),
--    jadi PK-nya belum tentu ada -- guard ini idempotent, aman dijalankan
--    ulang kapan pun.
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'paket_soal'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE paket_soal ADD PRIMARY KEY (id);
  END IF;
END $$;

-- Guard tambahan: paket_soal.id juga ternyata tidak auto-increment (tidak
-- ada default nextval/identity) -- INSERT tanpa id eksplisit gagal dengan
-- "null value in column id violates not-null constraint". Sama seperti
-- guard PK di atas, ini kemungkinan besar peninggalan tabel yang dibuat
-- lewat Table Editor tanpa opsi "Identity" dicentang.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'paket_soal' AND column_name = 'id' AND is_identity = 'YES'
  ) THEN
    ALTER TABLE paket_soal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Guard tambahan lagi: created_at juga tidak punya DEFAULT NOW() di tabel
-- live (baris yang di-insert tanpa created_at eksplisit jadi NULL, merusak
-- ORDER BY created_at DESC dan tampilan tanggal di frontend). Sekaligus
-- backfill baris lama yang sudah kadung NULL.
ALTER TABLE paket_soal ALTER COLUMN created_at SET DEFAULT NOW();
UPDATE paket_soal SET created_at = NOW() WHERE created_at IS NULL;

-- ============================================================================
-- 1. paket_soal: tambah `type`, lepas kepemilikan guru_id jadi audit trail
-- ============================================================================

ALTER TABLE paket_soal
  ADD COLUMN IF NOT EXISTS type VARCHAR(10) NOT NULL DEFAULT 'TKA'
    CHECK (type IN ('TKA', 'NON_TKA'));

ALTER TABLE paket_soal
  ADD COLUMN IF NOT EXISTS thumbnail VARCHAR(255);

-- guru_id lama berarti "milik guru ini" dan dipakai untuk memfilter query
-- (WHERE guru_id = ...) di paketSoal.controller.js. Di Revisi 8, bank soal
-- jadi bacaan bersama untuk semua guru -- kolom ini berubah makna jadi
-- "siapa yang menginput", bukan lagi dasar filter/kepemilikan. Di-rename
-- supaya jelas, dan constraint-nya dilonggarkan (nullable, ON DELETE SET
-- NULL bukan CASCADE) supaya menghapus akun guru tidak ikut menghapus
-- seluruh bank soal yang pernah dia input.
ALTER TABLE paket_soal RENAME COLUMN guru_id TO created_by_guru_id;
ALTER TABLE paket_soal ALTER COLUMN created_by_guru_id DROP NOT NULL;
ALTER TABLE paket_soal DROP CONSTRAINT IF EXISTS paket_soal_guru_id_fkey;
ALTER TABLE paket_soal
  ADD CONSTRAINT paket_soal_created_by_guru_id_fkey
    FOREIGN KEY (created_by_guru_id) REFERENCES guru(id) ON DELETE SET NULL;

-- Data seed yang sudah ada (kopi-gayo, tes, tes-lagi) semuanya pola Wordwall
-- -- default DEFAULT 'TKA' di atas otomatis menandai mereka TKA, sesuai
-- pertanyaan terbuka di PIVOT_PLAN.md §D. Tidak perlu UPDATE manual.

COMMENT ON COLUMN paket_soal.type IS 'TKA = aktivitas Wordwall (wordwall_url wajib jika published). NON_TKA = game React in-house, butir soal ada di tabel soal.';
COMMENT ON COLUMN paket_soal.created_by_guru_id IS 'Audit: siapa yang menginput paket ini. TIDAK dipakai untuk filter kepemilikan/akses -- bank soal bersifat bacaan bersama untuk semua guru (Revisi 8).';

-- ============================================================================
-- 2. soal: butir soal per paket, dipakai untuk game Non-TKA
--    (untuk paket TKA, tabel ini tetap kosong -- soalnya hidup di Wordwall)
-- ============================================================================

CREATE TABLE IF NOT EXISTS soal (
    id SERIAL PRIMARY KEY,
    paket_id INT NOT NULL REFERENCES paket_soal(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    stimulus TEXT,
    image VARCHAR(255),
    options JSONB NOT NULL DEFAULT '[]'::jsonb,
    correct_answer VARCHAR(10) NOT NULL,
    explanation TEXT,
    game_type VARCHAR(20) NOT NULL DEFAULT 'multiple_choice'
      CHECK (game_type IN ('multiple_choice', 'drag_drop', 'matching', 'image_selection')),
    order_number INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE soal ADD COLUMN IF NOT EXISTS explanation TEXT;

CREATE INDEX IF NOT EXISTS idx_soal_paket_id ON soal(paket_id);

COMMENT ON TABLE soal IS 'Butir soal individual untuk paket bertipe NON_TKA. options berbentuk JSON array, mis. [{"key":"A","text":"..."}, ...]; correct_answer merujuk ke salah satu key di options.';

-- ============================================================================
-- 3. hasil_diagnostik: hasil pengerjaan (menggantikan hasilData.js dummy)
--
--    CATATAN: belum ada akun siswa terpisah di sistem ini (lihat
--    PIVOT_PLAN.md §D) -- guru_id di sini adalah guru yang login/menjalankan
--    sesi, dan student_name tetap bebas teks seperti data prototype yang
--    ada sekarang. Sesuaikan kalau nanti akun siswa ditambahkan.
-- ============================================================================

CREATE TABLE IF NOT EXISTS hasil_diagnostik (
    id SERIAL PRIMARY KEY,
    paket_id INT REFERENCES paket_soal(id) ON DELETE SET NULL,
    guru_id INT REFERENCES guru(id) ON DELETE SET NULL,
    student_name VARCHAR(100),
    score NUMERIC(5,2) NOT NULL,
    correct_count INT NOT NULL DEFAULT 0,
    wrong_count INT NOT NULL DEFAULT 0,
    total_questions INT NOT NULL DEFAULT 0,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hasil_diagnostik_paket_id ON hasil_diagnostik(paket_id);
CREATE INDEX IF NOT EXISTS idx_hasil_diagnostik_guru_id ON hasil_diagnostik(guru_id);

COMMENT ON TABLE hasil_diagnostik IS 'Hasil pengerjaan Smart Diagnostic. Untuk TKA (Wordwall) baris ini hanya bisa diisi manual/tidak diisi otomatis (tidak ada API Wordwall). Untuk NON_TKA, website menghitung skor sendiri dan bisa insert otomatis.';

COMMIT;

-- ============================================================================
-- Rollback manual jika perlu (jalankan terpisah, bukan bagian migrasi ini):
--
-- BEGIN;
-- DROP TABLE IF EXISTS hasil_diagnostik;
-- DROP TABLE IF EXISTS soal;
-- ALTER TABLE paket_soal DROP CONSTRAINT IF EXISTS paket_soal_created_by_guru_id_fkey;
-- ALTER TABLE paket_soal RENAME COLUMN created_by_guru_id TO guru_id;
-- ALTER TABLE paket_soal ALTER COLUMN guru_id SET NOT NULL;
-- ALTER TABLE paket_soal ADD CONSTRAINT paket_soal_guru_id_fkey
--   FOREIGN KEY (guru_id) REFERENCES guru(id) ON DELETE CASCADE;
-- ALTER TABLE paket_soal DROP COLUMN IF EXISTS thumbnail;
-- ALTER TABLE paket_soal DROP COLUMN IF EXISTS type;
-- COMMIT;
-- ============================================================================
